Shihui
antvis/L7 pull request #1030
Opened 2022-03-31 09:48 UTC by 2912401452

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] commit message follows commit guidelines

##### Description of change

2022-04-07 02:34 UTC, lzxue requested changes

2022-04-07 02:34 UTC, lzxue commented on packages/core/src/services/layer/LayerService.ts
> +    if (option) {
这个写法有点冗余

2022-04-07 02:34 UTC, lzxue commented on packages/core/src/services/layer/LayerService.ts
> +    if (option) {
if (option) {
      if (option.mask) {
        option.parent.addMaskLayer(layer); 
这里写法怪怪的

2022-04-07 02:34 UTC, lzxue commented on packages/core/src/services/layer/LayerService.ts
> +    if (option) {
if (option) {
      if (option.mask) {
        option.parent.addMaskLayer(layer); 
这里写法怪怪的

2022-04-07 02:34 UTC, lzxue commented on packages/core/src/services/scene/ISceneService.ts
> +}
parent 是指？

2022-04-07 02:34 UTC, lzxue commented on packages/core/src/services/scene/ISceneService.ts
> +}
parent 是指？

2022-04-07 02:34 UTC, lzxue commented on packages/layers/src/core/LayerGroup.ts
> +export default class LayerGroup<ChildLayerStyleOptions = {}> extends BaseLayer
layergroup 怎么设置child 的渲染顺序

2022-04-07 02:34 UTC, lzxue commented on packages/layers/src/core/LayerGroup.ts
> +export default class LayerGroup<ChildLayerStyleOptions = {}> extends BaseLayer
layergroup 怎么设置child 的渲染顺序

2022-04-07 02:34 UTC, lzxue commented
masklayer 有么有比较单独存在？

2022-04-11 11:56 UTC, lvisei approved these changes

2022-04-13 07:13 UTC, merged