Shihui dev
antvis/L7 pull request #711
Opened 2021-06-21 04:15 UTC by 2912401452

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] commit message follows commit guidelines

##### Description of change

2021-06-21 13:13 UTC, lzxue commented on packages/layers/src/point/models/fill.ts
> +
上面这一坨是不是一个个有更好的写法

2021-06-22 01:55 UTC, 2912401452 commented on packages/layers/src/point/models/fill.ts
> +
收到

2021-06-22 01:55 UTC, 2912401452 commented on packages/layers/src/point/models/fill.ts
> +
收到

2021-06-22 02:18 UTC, lzxue requested changes
还需要好好想想

2021-06-22 02:18 UTC, lzxue commented on packages/layers/src/point/models/fill.ts
> +  ) {
这个参数搞搞成一个对象吧，类型不能使用any

2021-06-22 02:18 UTC, lzxue commented on packages/layers/src/point/models/fill.ts
> +      }
不要这样的枚举的去写

2021-06-22 02:18 UTC, lzxue commented on packages/layers/src/point/shaders/fill_vert.glsl
> +
这里的公共shader 能不能提取出来？

2021-06-22 02:18 UTC, lzxue commented on packages/layers/src/utils/dataMappingStyle.ts
> + * 根据传入参数 float 的类型和值做相应的操作
同样的问题， 不要一个个去写

2021-06-22 02:18 UTC, lzxue commented on packages/layers/src/core/BaseModel.ts
> +      } else {
如果没有参与数据映射也要预留数据空间吗？

2021-06-22 02:20 UTC, 2912401452 commented on packages/layers/src/point/models/fill.ts
> +  ) {
主要是参数类型不好定义

2021-06-22 02:20 UTC, 2912401452 commented on packages/layers/src/point/shaders/fill_vert.glsl
> +
这个可以的

2021-06-22 02:23 UTC, 2912401452 commented on packages/layers/src/core/BaseModel.ts
> +      } else {
这个是之前逻辑的一部分残留，不影响，但是也没有清除

2021-06-22 02:24 UTC, 2912401452 commented on packages/layers/src/core/BaseModel.ts
> +      } else {
不会执行到的，我改一下

2021-06-22 10:18 UTC, 2912401452 commented on packages/layers/src/point/models/fill.ts
> +  ) {
![0A270C97-EA22-4B02-870F-560872DD37F1](https://user-images.githubusercontent.com/42212176/122907752-0a7d6300-d386-11eb-88bc-c1b6213c3ecc.png)
还是自定义类型，不用对象，兼容之前的传参

2021-06-22 10:21 UTC, 2912401452 commented on packages/layers/src/point/models/fill.ts
> +      }
但是每个不同类型的 layer 对象需要判断的样式字段不同，这里比较长只是刚好 fill 支持所有的样式映射，大多数 layer 也就支持一两个吧（只有 opacity 比较常见）

2021-06-22 11:14 UTC, 2912401452 commented on packages/layers/src/utils/dataMappingStyle.ts
> + * 根据传入参数 float 的类型和值做相应的操作
但是这样子就很清楚啊

2021-07-12 12:12 UTC, merged